//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monobjc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monobjc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one parameter must be passed..
        /// </summary>
        internal static string AtLeastOneParameterMustBePassed {
            get {
                return ResourceManager.GetString("AtLeastOneParameterMustBePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block cannot be unmarshalled.
        /// </summary>
        internal static string BlockCannotBeUnmarshalled {
            get {
                return ResourceManager.GetString("BlockCannotBeUnmarshalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block is not a Delegate subclass.
        /// </summary>
        internal static string BlockIsNotDelegateSubclass {
            get {
                return ResourceManager.GetString("BlockIsNotDelegateSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call the variable arguments message &apos;{0}&apos; without a valid parameter list..
        /// </summary>
        internal static string CannotCallVarargsMessage {
            get {
                return ResourceManager.GetString("CannotCallVarargsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define class &apos;{0}&apos; because the super class &apos;{1}&apos; does not exists.
        /// </summary>
        internal static string CannotDefineClassBecauseSuperclassDoesNotExists {
            get {
                return ResourceManager.GetString("CannotDefineClassBecauseSuperclassDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define an Objective-C category from a null type.
        /// </summary>
        internal static string CannotDefineObjectiveCCategroyFromNullType {
            get {
                return ResourceManager.GetString("CannotDefineObjectiveCCategroyFromNullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot define an Objective-C class wrapper from a null type.
        /// </summary>
        internal static string CannotDefineObjectiveCClassFromNullType {
            get {
                return ResourceManager.GetString("CannotDefineObjectiveCClassFromNullType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a converter between {0} and {1}.
        /// </summary>
        internal static string CannotFindAConverter {
            get {
                return ResourceManager.GetString("CannotFindAConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate code to use by-ref parameter &apos;{0}&apos; as it is not supported.
        /// </summary>
        internal static string CannotGenerateCodeByRefParameterNotSupported {
            get {
                return ResourceManager.GetString("CannotGenerateCodeByRefParameterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class &apos;{0}&apos; cannot be found to define category from &apos;{1}&apos;.
        /// </summary>
        internal static string ClassNotFoundForCategory {
            get {
                return ResourceManager.GetString("ClassNotFoundForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have a constructor that takes an IntPtr parameter.
        /// </summary>
        internal static string ExposedTypeMustHaveAConstructorWithIntPtrParameter {
            get {
                return ResourceManager.GetString("ExposedTypeMustHaveAConstructorWithIntPtrParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must have a default constructor.
        /// </summary>
        internal static string ExposedTypeMustHaveADefaultConstructor {
            get {
                return ResourceManager.GetString("ExposedTypeMustHaveADefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ObjectiveCCategory attribute found for type &apos;{0}&apos;.
        /// </summary>
        internal static string NoCategoryAttributeFoundForType {
            get {
                return ResourceManager.GetString("NoCategoryAttributeFoundForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ObjectiveCClass attribute found for the base type of &apos;{0}&apos;.
        /// </summary>
        internal static string NoClassAttributeFoundForBaseType {
            get {
                return ResourceManager.GetString("NoClassAttributeFoundForBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ObjectiveCClass attribute found for type &apos;{0}&apos;.
        /// </summary>
        internal static string NoClassAttributeFoundForType {
            get {
                return ResourceManager.GetString("NoClassAttributeFoundForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name in ObjectiveCCategory attribute for type &apos;{0}&apos;.
        /// </summary>
        internal static string NoNameInCategoryAttributeForType {
            get {
                return ResourceManager.GetString("NoNameInCategoryAttributeForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCCategory[Name = &apos;{0}&apos;].
        /// </summary>
        internal static string ObjectiveCCategoryString {
            get {
                return ResourceManager.GetString("ObjectiveCCategoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCClass[Name = &apos;{0}&apos;, InterceptDealloc = &apos;{1}&apos;].
        /// </summary>
        internal static string ObjectiveCClassString {
            get {
                return ResourceManager.GetString("ObjectiveCClassString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCFramework[IsSystem = &apos;{0}&apos;].
        /// </summary>
        internal static string ObjectiveCFrameworkString {
            get {
                return ResourceManager.GetString("ObjectiveCFrameworkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCIVar[Name = &apos;{0}&apos;].
        /// </summary>
        internal static string ObjectiveCIVarString {
            get {
                return ResourceManager.GetString("ObjectiveCIVarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCMessage[Selector = &apos;{0}&apos;].
        /// </summary>
        internal static string ObjectiveCMessageString {
            get {
                return ResourceManager.GetString("ObjectiveCMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCProtocol[Name = &apos;{0}&apos;].
        /// </summary>
        internal static string ObjectiveCProtocolString {
            get {
                return ResourceManager.GetString("ObjectiveCProtocolString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectiveCUnderlyingType[Value = &apos;{0}&apos;, Is64Bits = &apos;{1}&apos;].
        /// </summary>
        internal static string ObjectiveCUnderlyingTypeString {
            get {
                return ResourceManager.GetString("ObjectiveCUnderlyingTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; of type &apos;{1}&apos; has an ObjectiveCMessage attribute without valid selector value.
        /// </summary>
        internal static string TheMethodOfTypeHasAnInvalidObjectiveCMessageAttribute {
            get {
                return ResourceManager.GetString("TheMethodOfTypeHasAnInvalidObjectiveCMessageAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; of type &apos;{1}&apos; has not ObjectiveCMessage attribute.
        /// </summary>
        internal static string TheMethodOfTypeHasNotObjectiveCMessageAttribute {
            get {
                return ResourceManager.GetString("TheMethodOfTypeHasNotObjectiveCMessageAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not inherit from IManagedWrapper.
        /// </summary>
        internal static string TypeDoesNotInheritsFromIManagedWrapper {
            get {
                return ResourceManager.GetString("TypeDoesNotInheritsFromIManagedWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; has no ObjectiveCProtocol attribute.
        /// </summary>
        internal static string TypeHasNoObjectiveCProtocolAttribute {
            get {
                return ResourceManager.GetString("TypeHasNoObjectiveCProtocolAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an interface.
        /// </summary>
        internal static string TypeIsNotAnInterface {
            get {
                return ResourceManager.GetString("TypeIsNotAnInterface", resourceCulture);
            }
        }
    }
}
