#!/bin/bash

case $(uname -r) in
	9.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.5/runtime" $@
	;;
	10.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.6/runtime" $@
	;;
	11.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.7/runtime" $@
	;;
	*)
		echo "Unsupported version of Mac OS X"
		uname -r
		exit 1
	;;
esac
