#!/bin/bash

case $(uname -r) in
	10.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.6/runtime" $@
	;;
	11.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.7/runtime" $@
	;;
	12.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.8/runtime" $@
	;;
	13.*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.9/runtime" $@
	;;
	*)
		"/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/monobjc-10.9/runtime" $@
	;;
esac
