//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monobjc.Foundation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monobjc.Foundation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array cannot be multidimensional..
        /// </summary>
        internal static string ArrayCannotBeMultidimensional {
            get {
                return ResourceManager.GetString("ArrayCannotBeMultidimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous result must be an &apos;NSResponderAsyncResult&apos; instance..
        /// </summary>
        internal static string AsynchronousResultMustBeNSResponderAsyncResult {
            get {
                return ResourceManager.GetString("AsynchronousResultMustBeNSResponderAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index cannot be negative..
        /// </summary>
        internal static string IndexCannotBeNegative {
            get {
                return ResourceManager.GetString("IndexCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index cannot exceed array&apos;s length..
        /// </summary>
        internal static string IndexCannotExceedArrayLength {
            get {
                return ResourceManager.GetString("IndexCannotExceedArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;InvokeRequired&apos; property is not supported on Mac OS X 10.4..
        /// </summary>
        internal static string InvokeRequiredNotSupported {
            get {
                return ResourceManager.GetString("InvokeRequiredNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space available..
        /// </summary>
        internal static string NotEnoughSpaceAvailable {
            get {
                return ResourceManager.GetString("NotEnoughSpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSArray is immutable..
        /// </summary>
        internal static string NSArrayIsImmutable {
            get {
                return ResourceManager.GetString("NSArrayIsImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSDictionary is immutable..
        /// </summary>
        internal static string NSDictionaryIsImmutable {
            get {
                return ResourceManager.GetString("NSDictionaryIsImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSEnumerator does not support reset..
        /// </summary>
        internal static string NSEnumeratorDoesNotSupportResetting {
            get {
                return ResourceManager.GetString("NSEnumeratorDoesNotSupportResetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSIndexSet is immutable..
        /// </summary>
        internal static string NSIndexSetIsImmutable {
            get {
                return ResourceManager.GetString("NSIndexSetIsImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSSet is immutable..
        /// </summary>
        internal static string NSSetIsImmutable {
            get {
                return ResourceManager.GetString("NSSetIsImmutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; class must implements the Delegate property..
        /// </summary>
        internal static string TheClassMustImplementTheDelegateProperty {
            get {
                return ResourceManager.GetString("TheClassMustImplementTheDelegateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not support the &apos;{1}&apos; message..
        /// </summary>
        internal static string TypeDoesNotSupportTheMessage {
            get {
                return ResourceManager.GetString("TypeDoesNotSupportTheMessage", resourceCulture);
            }
        }
    }
}
